### PR TITLE
add tag type SOLUM_M3_BWR_22_LITE

### PR DESCRIPTION
**Pull request by krikkirk**
Let me know if 0x47 is the correct hexadecimal to use. 
I will make PR for [Tag_FW_EFR32xG22](https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22) and [Tag_FW_nRF52811 ](https://github.com/OpenEPaperLink/Tag_FW_nRF52811) once this is merged.

### CODE REVIEW

**Comment by atc1441** [comment]
Hey, this size and resolution is already available under 45.json so this would be a double tagtype

**Comment by krikkirk** [comment]
Oh I missed that file. Shouldn't the definitions be added for the firmwares to use? 
I will make a new PR just for the definitions.

**Comment by atc1441** [comment]
It is added here, but feel free to add it to see repo as well for completness :)

https://github.com/OpenEPaperLink/Shared_OEPL_Definitions/blob/main/oepl-definitions.h#L63

**Comment by krikkirk** [comment]
Huh I was looking at https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/oepl-definitions.h The firmware repos are referencing the file you mentioned above.  I should be able to add the support for the 2.2 lite tag from there.

**Comment by atc1441** [comment]
The situation is a bit mixed since the main repo was split into the multiple repo solution

**Pull request closed without merging**
