### PR TITLE
add support for lilygo t-panel

### PR DESCRIPTION
**Pull request by mhwlng**
https://www.lilygo.cc/products/t-panel-s3

### CODE REVIEW

**Comment by skiphansen** [comment]
Great work!  One question/comment:  has Arduino_GFX-1.3.7 been modified or is it "off the shelf"?

If it hasn't been modified it would be better to just add it to platformio.ini as a lib_dep rather than adding it to the source tree.

**Comment by mhwlng** [comment]
it's this library from lilygo
https://github.com/Xinyuan-LilyGO/T-Panel/tree/arduino-esp32-libs_V2.0.14/libraries/Arduino_GFX-1.3.7
and it's not the same as the original library with the same version
https://github.com/moononournation/Arduino_GFX/releases/tag/v1.3.7
that doesn't work

**Comment by mhwlng** [comment]
Hi
I managed to find a way to remove the lilygo lib2\Arduino_GFX-1.3.7 files and switch to the official  moononournation/GFX Library for Arduino@^1.4.9
is everything ok now ?

**Comment by jonasniesner** [comment]
Great, we have to run a few more tests on our side but looks better now

**Comment by mhwlng** [comment]
unfortunately I spoke too soon :-(
after a power cycle, the display stays dark with the 'official' version and is ok with the lilygo version
I'm still checking if I can get rid of the lib2\Arduino_GFX-1.3.7 library

**Comment by mhwlng** [comment]
the OpenEPaperLink_Mini_AP build fails with an out of memory error ?

Error: The program size (1313722 bytes) is greater than maximum allowed (1310720 bytes)
*** [checkprogsize] Explicit exit, status 1
RAM:   [==        ]  18.1% (used 59332 bytes from 327680 bytes)
Flash: [==========]  100.2% (used 1313722 bytes from 1310720 bytes)

I can't find anything in my code that would cause that ?

I do see that the TFT_eSPI library is referenced for all environments, not only for the ones with a display.
But that was always the case. I didn't change that?

**Comment by jonasniesner** [comment]
Yea, I kinda expected it to fail, that one is on the limit of what is possible. I will checked if it also fails on the main

**Comment by nlimper** [comment]
TFT_eSPI is needed for all environments, it's used as the drawing canvas for many of the built in content in the AP. It would be ideal if it could be used instead of Arduino_GFX-1.3.7, as in theory TFT_eSPI should also be capable of driving your screen.

The mini_AP firmware space is very tight. If there has been a new release of the IDE, and it has become bigger, it might not fit, and we have to remove some extra functionality.

**Comment by mhwlng** [comment]
>>it's used as the drawing canvas for many of the built in content in the AP
of course, you're right. I should have thought about that :-)

>>TFT_eSPI should also be capable of driving your screen.
I have not found this display in the list of supported controllers on:
https://github.com/Bodmer/TFT_eSPI
the only library that supports this display is the one from lilygo, as far as I can find
not even the original moononournation/GFX Library works (any version).
I found changes to a GFX method, that only exists in the liligo 'fork' and that prevents adding the standard library.
I am putting the lib2\Arduino_GFX-1.3.7 back, to make it work again, but I'm working to remove cpp/h files that are not needed

**Comment by skiphansen** [comment]
> unfortunately I spoke too soon :-( after a power cycle, the display stays dark with the 'official' version and is ok with the lilygo version I'm still checking if I can get rid of the lib2\Arduino_GFX-1.3.7 library

You can specify a specific github source in platformio.ini it doesn't have to be the "official" repo.  i.e.
```

**Comment by mhwlng** [comment]
I tried to add https://github.com/Xinyuan-LilyGO/T-Panel/tree/arduino-esp32-libs_V2.0.14/libraries/Arduino_GFX-1.3.7
but platformio gave an error I think it needs a library.json file, which lilygo hasn't added.

**Comment by skiphansen** [comment]
> I tried to add https://github.com/Xinyuan-LilyGO/T-Panel/tree/arduino-esp32-libs_V2.0.14/libraries/Arduino_GFX-1.3.7 but platformio gave an error I think it needs a library.json file, which lilygo hasn't added.

That's unfortunate!  I wonder if they would accept a pull request, they seem pretty open.

I like their stuff in fact I just ordered a lilygo t-panel after I saw your post in discord.

**Comment by mhwlng** [comment]
I added lilygo lib2\Arduino_GFX-1.3.7 back and removed all unused files. 
the file list went from 166 files to 15 files! 
and this library is not linked in the existing environments. only the lilygo one.

**Comment by skiphansen** [comment]
> I added lilygo lib2\Arduino_GFX-1.3.7 back and removed all unused files. the file list went from 166 files to 15 files! and this library is not linked in any of the existing environments. only the new lilygo environment.

Perfect !

**Comment by mhwlng** [comment]
Hi
I found that the AP restarted every few hours. 
I disabled the BLE functionality (I have 2 gicisky labels) and the problem went a way. 
the AP has now  been stable for 18 hours, without bluetooth.
Is this a known problem ?

**Comment by atc1441** [comment]
Hey, yes BLE is that unstable.
You can flash the Zigbee firmware onto the Gicisky if the are TLSR based so you dont need BLE anymore.
Firmware is in the binaries folder for some types
https://atc1441.github.io/BLE_EPaper_OTA.html

**Comment by jonasniesner** [comment]
I got my t-panel today and am going to do some tests on the hardware

**Comment by jonasniesner** [comment]
Was the AP stable for you?

**Comment by mhwlng** [comment]
> Was the AP stable for you?

yes, without the BLE stuff it's fine

**Pull request merged**
