### PR TITLE
Add option for AP discovery type

### PR DESCRIPTION
**Pull request by jonnybergdahl**
My WiFi mesh is not working correctly with multicast, so I added an option in the settings to use broadcast instead.

### CODE REVIEW

**Comment by nlimper** [comment]
Nice. Some comments: before we can merge:
Please use consistant spacing: intentation is done by spaces throughout the whole codebase, but you used tabs (I know, I hate using spaces too, but it's what it is...).
Also, typo in index.html line 467 ('Bbroadcast').
And please don't check in .gz files when the uncompressed files haven't changed.

**Comment by jonnybergdahl** [comment]
Ok, fixed the tabs vs spaces issue. Not sure how to fix the gzip thing though, CLion told me all files were changed!?!?

**Comment by nlimper** [comment]
I assume you used `gzip_wwwfiles.py` for gzipping? Sadly, the different windows/mac/linux versions of gzip don't result in byte identical files. If you didn't use gzip_wwwfiles.py: the date/time when the compression took place is kept within the .gz file, so that results in a different output file for every time you compress the files.
Just revert the files what are not changed (i.e., everything exept index.html).

**Comment by jonnybergdahl** [comment]
I did use `gzip_wwwfiles.py` yes, but I am on Mac so that probably explains it. I did make changes to `main.js` as well though. I pushed a new commit that should solve that issue.

**Comment by jonnybergdahl** [comment]
Seems my change to the `apconfig.json` resulted in a NoMemory error at startup so I increased the JSON buffer.

**Comment by jonasniesner** [comment]
Is this PR ready to be merged?

**Pull request merged**
